This book is for examples from https://developers.google.com/codelabs/tensorflow-1-helloworld?continue=https%3A%2F%2Fdevelopers.google.com%2Flearn%2Fpathways%2Ftensorflow%23codelab-https%3A%2F%2Fdevelopers.google.com%2Fcodelabs%2Ftensorflow-1-helloworld#2

In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

2025-01-29 12:02:54.389988: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-29 12:02:54.402682: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-29 12:02:54.541178: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-29 12:02:54.773583: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1738152174.959673  520314 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1738152175.01

Define and compile the neural network
Next, create the simplest possible neural network. It has one layer, that layer has one neuron, and the input shape to it is only one value.

In [2]:
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

/opt/conda/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2025-01-29 12:03:06.045673: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


When the computer is trying to learn that, it makes a guess, maybe Y=10X+10. The loss function measures the guessed answers against the known correct answers and measures how well or badly it did.

Next, the model uses the optimizer function to make another guess. Based on the loss function's result, it tries to minimize the loss. At this point, maybe it will come up with something like Y=5X+5. While that's still pretty bad, it's closer to the correct result (the loss is lower).

First, here's how to tell it to use mean_squared_error for the loss and stochastic gradient descent (sgd) for the optimizer. You don't need to understand the math for those yet, but you can see that they work!

In [3]:
model.compile(optimizer='sgd', loss='mean_squared_error')

Next, feed some data. In this case, you take the six X and six Y variables from earlier. You can see that the relationship between those is that Y=3X+1, so where X is -1, Y is -2.

In [4]:
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-2.0, 1.0, 4.0, 7.0, 10.0, 13.0], dtype=float)
print(xs)
print(ys)

[-1.  0.  1.  2.  3.  4.]
[-2.  1.  4.  7. 10. 13.]


Now you have all the code you need to define the neural network. The next step is to train it to see if it can infer the patterns between those numbers and use them to create a model.

4. Train the neural network
5. 
The process of training the neural network, where it learns the relationship between the X's and Y's, is in the model.fit call. That's where it will go through the loop before making a guess, measuring how good or bad it is (the loss), or using the optimizer to make another guess. It will do that for the number of epochs that you specify. When you run that code, you'll see the loss will be printed out for each epoch.

In [13]:
model.fit(xs, ys, epochs=250)

Epoch 1/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 7.8481e-04
Epoch 2/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 7.6868e-04
Epoch 3/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 7.5290e-04
Epoch 4/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 7.3743e-04
Epoch 5/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 7.2228e-04
Epoch 6/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 7.0745e-04
Epoch 7/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 6.9291e-04
Epoch 8/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 6.7868e-04
Epoch 9/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 6.6474e-04
Epoch 10/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 6.5109e-04
Epoch 11/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 6.3772e-04
Epoch 12/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 6.2461e-04
Epoch 13/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 6.1179e-04
Epoch 14/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 5.9922e-04
Epoch 15/250
1/1 ━━━━━━━━━━━━

By the time the training is done, the loss is extremely small, showing that our model is doing a great job of inferring the relationship between the numbers. You probably don't need all 500 epochs and can experiment with different amounts. As you can see from the example, the loss is really small after only 50 epochs, so that might be enough!

Lets use this model now

In [14]:
n = np.float64(10.0)
p = np.float64(13.0)

print(model.predict(np.array([[n],[p]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
[[31.00617]
 [40.00885]]


Neural networks deal with probabilities, so it calculated that there is a very high probability that the relationship between X and Y is Y=3X+1, but it can't know for sure with only six data points. The result is very close to 31, but not necessarily 31.